# Generated by Django 5.1.4 on 2025-01-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, verbose_name='Display name')),
                ('company_name', models.CharField(max_length=70, verbose_name='Company name')),
                ('company_id', models.CharField(max_length=30, verbose_name='Company ID')),
                ('company_vat', models.CharField(max_length=20, verbose_name='Company VAT')),
                ('birth_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Birth number')),
                ('entity_type', models.IntegerField(choices=[(1, 'Business'), (2, 'Non-profit'), (3, 'Contributory organization')], verbose_name='Entity type')),
                ('legal_entity_type', models.IntegerField(choices=[(1, 'Natural person'), (2, 'Legal entity')], verbose_name='Legal entity type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary contact')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity', verbose_name='Entity')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50, verbose_name='Account name')),
                ('bank_account_number', models.CharField(max_length=30, verbose_name='Bank account number')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('swift', models.CharField(max_length=11, verbose_name='SWIFT code')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank name')),
                ('currency', models.CharField(max_length=3, verbose_name='Account currency')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primary account')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity', verbose_name='Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('address_type', models.IntegerField(choices=[(0, 'Billing'), (1, 'Shipping'), (2, 'Other')], verbose_name='Address type')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entity', verbose_name='Entity')),
            ],
        ),
    ]
