# Generated by Django 5.1.4 on 2025-08-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(db_index=True, max_length=32, verbose_name='Card Number')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('date', models.DateField(db_index=True, verbose_name='Event Date')),
                ('time', models.TimeField(verbose_name='Event Time')),
                ('object_id', models.CharField(max_length=20, verbose_name='Object ID')),
                ('reader_id', models.CharField(max_length=20, verbose_name='Reader ID')),
                ('event_type', models.CharField(choices=[('1', 'Entry'), ('2', 'Exit'), ('3', 'Break Start'), ('4', 'Door Unlock')], max_length=2, verbose_name='Event Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_events', to='agent.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Card Event',
                'verbose_name_plural': 'Card Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
