"""
Django settings for dym project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os

DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"
print(f"Raw value of DEVELOPMENT_MODE: '{DEVELOPMENT_MODE}'")

if DEVELOPMENT_MODE:
    print("Běžím ve vývojovém režimu")
else:
    print("Běžím v produkci")


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o^+exby0xsr8v+d%iyu96j#vt#2(c8fj!ys#=_rkwm1+oalu0m'

# SECURITY WARNING: don't run with debug turned on in production!


#ALLOWED_HOSTS = []
if DEVELOPMENT_MODE:
    DEBUG = True
    ALLOWED_HOSTS = ['10.20.30.70','10.20.30.71', 'localhost', '127.0.0.1']
    CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "https://127.0.0.1",
    ]
else:
    DEBUG = False
    ALLOWED_HOSTS = ['localhost', '127.0.0.1','194.182.86.168', 'abiz.cz', 'www.abiz.cz']


# Povolit jen HTTPS připojení
if DEVELOPMENT_MODE:
    SET_HTTPS = False
else:
    SET_HTTPS = True

if SET_HTTPS:
    SECURE_SSL_REDIRECT = True  # Přesměrování HTTP → HTTPS
    SESSION_COOKIE_SECURE = True  # Session cookies pouze přes HTTPS
    CSRF_COOKIE_SECURE = True  # CSRF cookie pouze přes HTTPS
    SECURE_HSTS_SECONDS = 31536000  # HSTS (1 rok)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Povolit HTTPS přes reverse proxy
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o^+exby0xsr8v+d%iyu96j#vt#2(c8fj!ys#=_rkwm1+oalu0m'






LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL  = '/'
LOGOUT_REDIRECT_URL = '/'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'agent',
    'dym',
    'core',
    'orders',
    'products',
    'entities',
    'integral',
    'ingest',
    'entrix',
    'rfid',          
    'mock',          
    # ... ostatní aplikace
    'widget_tweaks',
]

if DEVELOPMENT_MODE:
    INSTALLED_APPS += ['django_extensions']
    

AUTH_USER_MODEL = 'agent.AppUser'

MIDDLEWARE = [
    'dym.middleware.LogHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Důležité pro i18n
]

ROOT_URLCONF = 'dym.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Přidej vlastní context processor:
                'core.context_processors.current_company_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'dym.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
if DEVELOPMENT_MODE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'dym',
            'USER': 'dym_admin',
            'PASSWORD': 'dymadmin',
            'HOST': 'localhost',  # IP address of your PostgreSQL server
            'PORT': '5433',  # Default PostgreSQL port
            #    'OPTIONS': {
            #       'charset': 'utf8mb4',
        #    }        
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'dym',
            'USER': 'dym_admin',
            'PASSWORD': 'dymadmin',
            'HOST': 'localhost',  # IP address of your PostgreSQL server
            'PORT': '5432',  # Default PostgreSQL port
            #    'OPTIONS': {
        #       'charset': 'utf8mb4',
        #    }        
    
        }
    }
    



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('cs', _('Czech')),
]

USE_L10N = True
LANGUAGE_CODE = 'en-us'
# Nastavení cookies pro jazyk
TIME_ZONE = 'Europe/Prague'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Define the directory where collected static files will be stored
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SNK settings.py

CURRENT_COMPANY = "dym"
CURRENT_COMPANY = "veros"

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE
    INTERNAL_IPS = ['127.0.0.1',
                    '10.20.30.70',]

#Aplikace ingest
SECRET_INGEST_TOKEN = 'a64a569afc769a89072e0abb21c20d0ea815860708f6436e95897c70793fdc3c'

# Podminky ruznych logu, tohle je log ze souboru middleware.py
LOG_HOST_MIDDLEWARE_ENABLED = False
LOGGING_ENABLED = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if LOGGING_ENABLED else [],
            'level': 'DEBUG' if LOGGING_ENABLED else 'WARNING',
            'propagate': True,
        },
    },
}
