# Generated by Django 5.1.4 on 2025-01-28 12:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Order number')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Order date')),
                ('required_date', models.DateField(verbose_name='Required delivery date')),
                ('shipped_date', models.DateField(blank=True, null=True, verbose_name='Shipped date')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled'), (5, 'Awaiting Payment'), (6, 'Returned'), (7, 'Order Problem')], verbose_name='Status')),
                ('description_HTML', models.TextField(blank=True, max_length=255, verbose_name='Comment in HTML format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Invoice issue date')),
                ('due_date', models.DateField(verbose_name='Invoice due date')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total invoice amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax amount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal amount')),
                ('status', models.IntegerField(choices=[(0, 'Issued'), (1, 'Paid'), (2, 'Awaiting Payment'), (3, 'Canceled')], verbose_name='Status')),
                ('description_HTML', models.TextField(blank=True, max_length=255, verbose_name='Comment about the invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price each')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ordered product')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Quantity sold')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sale price')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Sale date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='entities.entity', verbose_name='Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product', verbose_name='Sold product')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
