# Generated by Django 5.1.4 on 2025-01-07 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Product name')),
                ('order_date', models.DateField(verbose_name='Order date')),
                ('required_date', models.DateField(verbose_name='Required delivery date')),
                ('shipped_date', models.DateField(verbose_name='Shipped date')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled'), (5, 'Awaiting Payment'), (6, 'Returned'), (7, 'Order Problem')], verbose_name='Status')),
                ('description_HTML', models.CharField(max_length=255, verbose_name='Comment in HTML format')),
                ('created_at', models.DateTimeField(default='CURRENT_TIMESTAMP', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='Invoice issue date')),
                ('due_date', models.DateField(verbose_name='Invoice due date')),
                ('payment_date', models.DateField(verbose_name='Payment date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total invoice amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax amount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal amount')),
                ('status', models.IntegerField(choices=[(0, 'Issued'), (1, 'Paid'), (2, 'Awaiting Payment'), (3, 'Canceled')], verbose_name='Status')),
                ('description_HTML', models.CharField(max_length=255, verbose_name='Comment about the invoice')),
                ('created_at', models.DateTimeField(default='CURRENT_TIMESTAMP', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(default='CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP', verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.entity', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price each')),
                ('created_at', models.DateTimeField(verbose_name='Created at')),
                ('updated_at', models.DateTimeField(verbose_name='Updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
        ),
    ]
