# Generated by Django 5.1.4 on 2025-08-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Permission Name')),
            ],
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True, verbose_name='Card ID')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to='agent.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'RFID Card',
                'verbose_name_plural': 'RFID Cards',
                'ordering': ['card_id'],
            },
        ),
        migrations.CreateModel(
            name='RFIDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('denied', 'Access Denied')], max_length=50)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='rfid.rfidcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfid.permission')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='rfid.rfidcard')),
            ],
            options={
                'unique_together': {('card', 'permission')},
            },
        ),
    ]
