# Generated by Django 5.1.4 on 2025-01-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='account_name',
            new_name='account_owner',
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(max_length=30, verbose_name='Entity Type'),
        ),
    ]
