# Generated by Django 5.1.4 on 2025-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='birth_number',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='legal_entity_type',
        ),
        migrations.AlterField(
            model_name='entity',
            name='company_name',
            field=models.CharField(max_length=70, verbose_name='Company name (First name, Last name)'),
        ),
    ]
