# Generated by Django 5.1.4 on 2025-01-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_rename_account_name_bankaccount_account_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_owner',
            field=models.CharField(max_length=50, verbose_name='Account owner'),
        ),
    ]
