# Generated by Django 5.1.4 on 2025-01-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_address_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity', verbose_name='Entity'),
        ),
    ]
