# Generated by Django 5.1.4 on 2025-01-17 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_bankaccount_account_owner'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'verbose_name': 'Packaging', 'verbose_name_plural': 'Packagings'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_HTML',
        ),
        migrations.AlterField(
            model_name='packaging',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='products.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='entities.entity', verbose_name='Vendor'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, verbose_name='Product name')),
                ('order_date', models.DateField(verbose_name='Order date')),
                ('required_date', models.DateField(verbose_name='Required delivery date')),
                ('shipped_date', models.DateField(verbose_name='Shipped date')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Shipped'), (3, 'Delivered'), (4, 'Canceled'), (5, 'Awaiting Payment'), (6, 'Returned'), (7, 'Order Problem')], verbose_name='Status')),
                ('description_html', models.CharField(max_length=255, verbose_name='Comment in HTML format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='entities.entity', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(verbose_name='Invoice issue date')),
                ('due_date', models.DateField(verbose_name='Invoice due date')),
                ('payment_date', models.DateField(verbose_name='Payment date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total invoice amount')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax amount')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal amount')),
                ('status', models.IntegerField(choices=[(0, 'Issued'), (1, 'Paid'), (2, 'Awaiting Payment'), (3, 'Canceled')], verbose_name='Status')),
                ('description_html', models.CharField(max_length=255, verbose_name='Comment about the invoice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='entities.entity', verbose_name='Customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='products.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('price_each', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='description_html',
            field=models.CharField(default='', max_length=255, verbose_name='Product description HTML file'),
        ),
    ]
