# Generated by Django 5.1.4 on 2025-01-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_packaging_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='name',
            field=models.CharField(default='Unnamed Packaging', editable=False, max_length=30, verbose_name='Packaging name'),
        ),
    ]
