# Generated by Django 5.1.4 on 2025-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_packaging_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='name',
            field=models.CharField(default='Unnamed Packaging', max_length=30, verbose_name='Packaging name'),
        ),
    ]
