# Generated by Django 5.1.4 on 2025-01-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_bankaccount_account_owner'),
        ('products', '0004_alter_packaging_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='product',
        ),
        migrations.AddField(
            model_name='packaging',
            name='products',
            field=models.ManyToManyField(related_name='packagings', to='products.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='entities.entity', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(blank=True, null=True, verbose_name='Shipped date'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='qty',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='packaging',
            name='name',
            field=models.CharField(default='Unnamed Packaging', editable=False, max_length=255, verbose_name='Packaging name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to='entities.entity', verbose_name='Vendor'),
        ),
        migrations.AddConstraint(
            model_name='packaging',
            constraint=models.CheckConstraint(condition=models.Q(('gross_weight__gt', models.F('net_weight'))), name='gross_weight_gt_net_weight'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('qty_reserved__lte', models.F('qty_in_stock'))), name='reserved_not_exceed_stock'),
        ),
    ]
