# Generated by Django 5.1.4 on 2025-01-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_packaging_product_packaging_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packaging',
            name='products',
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity of products in this packaging')),
                ('packaging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packagings', to='products.packaging', verbose_name='Packaging')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packagings', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Packaging',
                'verbose_name_plural': 'Product Packagings',
            },
        ),
    ]
